baseURL : "https://banalian.github.io"
languageCode : "fr-fr"
title : "Lilian Pouvreau's Portfolio"
theme: hugo-profile


outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

#Menus:
  #main:
    #- identifier: blog
    #  name: Blog
    #  title: Blog posts
    #  url: /blogs
    #  weight: 1
    #- identifier: gallery
    #  name: Gallery
    #  title: Blog posts
    #  url: /gallery
    #  weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Lilian Pouvreau"
  description: Portfolio et CV de Lilian Pouvreau
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    defaultTheme: "dark" # light

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

    darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
      primaryColor: "#3DD2CC"
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Lilian Pouvreau" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Bonjour, mon nom est"
    title: "Lilian Pouvreau."
    subtitle: "Maître et ingénieur français en informatique"
    content: "Je suis un ingénieur en informatique (UQAC et Polytech Tours). J'ai une passion pour le développement, dont celui de jeux vidéo."
    image: /images/me.jpg
    bottomImage:
      enable: true
    roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Curriculum Vitae"
      url: "CV_Lilian_Canada.pdf"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/Banalian
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/lilian-pouvreau/
      #customIcons:
      #  - icon: /fav.png
      #    url: "https://example.com"

  # About
  about:
    enable: true
    title: "À propos de moi"
    image: "/images/me.jpg"
    content: |-
      Je suis un Maître et Ingénieur en informatique (UQAC et Polytech Tours). J'ai une passion pour le développement, dont celui de jeux vidéo.
      Je travaille sur plusieurs projets dans le cadre professionnel et personnel, comme par exemple le développement d'un plugin pour Trackmania ayant des milliers de téléchargements.
    skills:
      enable: true
      title: |-
        Voici les langagues et outils avec lesquels j'ai eu l'occasion de travailler dernièrement:
      items:
        - "C++"
        - "Lua"
        - "C#"
        - "Java"
        - "Angelscript"
        - "Python"
        - "Git"
        - "Perforce"
        - "Unity"
        - "Unreal Engine"

  # Experience
  experience:
    enable: true
    title: "Expérience professionnelle"
    items:
      - job: "Développeur"
        company: "Beenox"
        companyUrl: "https://beenox.com/"
        date: "Septembre 2024 - Aujourd'hui"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        info:
          enable: false
        content: "Travail sur Call of Duty (plusieurs projets) en UI et Automation."

      - job: "Programmeur en Informatique"
        company: "Boutique Imaginaire"
        companyUrl: "https://imaginaire.com/"
        date: "Juin 2024 - Septembre 2024"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        info:
          enable: false
        content: "Travail sur plusieurs projets internes de différentes envergures, allant de l'IA à des plus petites tâches d'automatisation."

      - job: "Stage en programmation UI Eng"
        company: "Beenox"
        companyUrl: "https://beenox.com/"
        date: "Septembre 2023 - Mars 2024"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        info:
          enable: false
        content: "Travail sur deux titres (Call of Duty Modern Warfare III et un titre non annoncé). Réalisation de features en Interface Utilisateur, côté ingénierie, et bugfix sur ces deux titres. Réalisation d'un outil pour Perforce."

      - job: "Stage développeur"
        company: "Worldline"
        companyUrl: "https://fr.worldline.com/fr/home.html"
        date: "Juin 2022 - Août 2022"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        info:
          enable: false
        content: "Développement d'un outil interne de génération de rapports concernant les dépendances des projets de l'équipe. Outil réalisé en Java, puis intégré dans un pipeline Jenkins utilisant une librairie réalisée par l'équipe."

      - job: "Projet en laboratoire informatique"
        company: "UQAC"
        companyUrl: "https://liara.uqac.ca/"
        date: "Mai 2020 - Juin 2020"
        featuredLink:
          enable: false
          url: "https://example.com"
        info:
          enable: false
        content: "Développement d'algorithmes en intelligence artificielle dans les jeux vidéo. Plus particulièrement, un travail sur l'algorithme du Monte Carlo Tree Search afin de réaliser une intelligence artificielle capable de jouer à des jeux comme snake. "
      - job: "Serveur (Job étudiant)"
        company: "Villa Or"
        companyUrl: "https://villador49.com/"
        date: "Jan 2018 - Nov 2019"
        info:
          enable: false
        featuredLink:
          enable: false
          url: "https://example.com"
        content: "Travail en tant que serveur dans le restaurant Villa d'Or. Cet emploi m'a permis de développer mon autonomie, ma rapidité ainsi que ma capacité de travail d'équipe et de relation clientèle."

  # Education
  education:
    enable: true
    title: "Formation"
    index: false
    items:
      - title: "Double-Diplôme : Maîtrise en Informatique"
        school:
          name: "Université du Québec à Chicoutimi"
          url: "https://uqac.ca"
        date: "2022 - 2024"
        content: |-
          Spécialité jeux vidéo 
          - Travail sur plusieurs concepts dans le domaine des jeux vidéo comme moteur de jeux, réseau, conception et jeux sérieux
      - title: "Formation Ingénieur Informatique"
        school:
          name: "Polytech Tours"
          url: "https://polytech.univ-tours.fr/"
        date: "2020 - 2024"
        content: |-
          - Filière Systèmes d'information
      - title: "DUT GEII"
        school:
          name: "IUT d'Angers"
          url: "https://www.univ-angers.fr/fr/acces-directs/facultes-et-instituts/iut.html"
        date: "2018 - 2020"
        content: |-
          Diplôme universitaire de technologie en Génie Électrique et Informatique Industrielle. Équivalent d'un Baccalauréat au Québec.
          - Spécialité Informatique
          - Séjour d'études à l'UQAC (Canada) durant 4 mois de janvier à avril 2020
      - title: "Baccalauréat STI2D (Mention Très bien)"
        school:
          name: "Lycée Chevrollier, Angers"
          url: "https://chevrollier.paysdelaloire.e-lyco.fr/"
        date: "2015 - 2018"
        content: |-
          Baccalauréat Sciences et Technologie de l'Industrie et du Développement Durable. Equivalent d'un DEC au Québec
          - Spécialité SIN (Systèmes d'Information et Numérique)

  # Achievements
  achievements:
    enable: true
    title: "Accomplissements"
    items:
      - title: Game Maker's Toolkit Game Jam 2024
        content: J'ai participé à l'édition 2024 de la GMTK's Game Jam avec un ami. Le thème était "Built to Scale". Nous avons fini 637éme sur plus de 7600 jeux. Le jeu est disponible sur itch.io.
        url: https://banalian.itch.io/bar-of-demanding-gods
      - title: Game Maker's Toolkit Game Jam 2023
        content: J'ai eu l'occasion de réaliser un jeu vidéo en 48h dans une équipe de 4 personnes dans le cadre du Game Maker's Toolkit Game Jam 2023. Le thème était "Reversed roles". Nous avons fini 669éme sur près de 6900 jeux. Le jeu est disponible sur itch.io.
        url: https://banalian.itch.io/rebrick
      - title: Jum Jam 2023
        content: J'ai eu l'occasion de réaliser un jeu vidéo seul en 48h dans le cadre du Jum Jam 2023, une game jam entre amis. Le thème était "One Room". Le jeu est disponible sur itch.io.
        url: https://banalian.itch.io/roomblock
    #  - title: Achievement 1
    #    content: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
    #    url: https://example.com

  # projects
  # TODO
  projects:
    enable: true
    title: "Projets"
    #items:
    #  - title: Lorem ipsum dolor sit amet
    #    content: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
    #    image: /projects/Lorem/main.jpg
    #    featured:
    #      name: Page du projet
    #      link: 
    #    badges:
    #      - "Unity"
    #      - "C#"

  #Contact
  contact:
    enable: true
    title: "Contact"
    content: N'hésitez pas à me contacter. Je serai ravi de répondre à vos questions ou demandes.
    email: pouvreaulilian@gmail.com
    btnName: Contactez-moi !
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Posts récents
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/Banalian
      linkedin: https://linkedin.com/in/lilian-pouvreau/

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: " minutes de lecture"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Lire"
    toc: "Table des matières"
    copyright: "Tous droits réservés"
    pageNotFound: "Page non trouvée"
    emailText: "Regardez ce site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"
